name: Go tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Modules
        run: go mod download -json

      - name: Go lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
          go vet ./...

      - name: Run version command
        env:
          TZ: Asia/Shanghai
        run: |
          make appVersion=1.3.3 projectName=billing
          chmod +x ./billing
          ./billing version
